### ISSUE TITLE
Don't work in firefox

### ISSUE THREAD

**Issue by jcubic** [developit/simple-element-resize-detector#6]
It don't work in Firefox, the event is not fired when there is `visibility:hidden`. If you remove it it's fired.

**Comment by NekR** [comment]
Yeah, it's known thing. More discussion here: https://github.com/developit/simple-element-resize-detector/pull/5

@developit I think that had to be already merged..

**Comment by NekR** [comment]
I mean, with correct fix for Firefox, of course

**Comment by developit** [comment]
Is it good to merge?

**Comment by jcubic** [comment]
it still will not work in Firefox if `visibility:hidden` will not be removed.

**Comment by developit** [comment]
Yup, just meant there was already an open PR for discussing the specific CSS properties to set.  IMO it should be:

```css
position:absolute;top:-100%;width:100%;height:100%;margin:1px 0 0;border:0;opacity:0;pointer-events:none;
```

I have use that setup in other projects with good success across browsers.  It can result in an invisible unclickable 1px bar atop resize-observed elements in IE9 though. For me that was okay. @NekR suggested some JavaScript to work around that by setting `visibility:hidden` only for IE11 and prior.

**Comment by jcubic** [comment]
I've seen the #5 PR, it don't remove visibility hidden only `left:0;top:-100%; opacity:0;`

**Comment by developit** [comment]
Yup, that's why it hasn't been merged yet :)
